services:
  web:
    build: .
    container_name: smartfitness-web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.5
    container_name: smartfitness-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: smartfitness
      MYSQL_INITDB_SKIP_TZINFO: "yes"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/smartfitness.sql:/docker-entrypoint-initdb.d/smartfitness.sql
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  phpmyadmin:
    container_name: smartfitness-phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data:
